{"variants":[{"paths":["\/documentation\/sidemenu\/sidemenusegue\/perform()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sidemenu\/sidemenusegue\/perform()"]}],"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/perform()"},"abstract":[{"type":"text","text":"Performing the segue, will change the corresponding view controller of side menu to "},{"code":"destination","type":"codeVoice"},{"type":"text","text":" view controller."},{"type":"text","text":" "},{"type":"text","text":"This method is called when loading from storyboard."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","title":"perform()","symbolKind":"method","modules":[{"name":"SideMenu"}],"externalID":"c:@M@SideMenu@objc(cs)SideMenuSegue(im)perform","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"perform","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"perform"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"perform","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"title":"SideMenuController","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","url":"\/documentation\/sidemenu\/sidemenucontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SideMenuController","kind":"identifier"}],"navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"type":"topic","kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue":{"type":"topic","kind":"symbol","abstract":[{"text":"Custom Segue that is required for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"},{"text":" to be used in Storyboard.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SideMenuSegue","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SideMenuSegue"}],"url":"\/documentation\/sidemenu\/sidemenusegue","title":"SideMenuSegue","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","role":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"type":"topic","title":"SideMenu","abstract":[],"url":"\/documentation\/sidemenu","role":"collection","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/perform()":{"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/perform()","title":"perform()","abstract":[{"text":"Performing the segue, will change the corresponding view controller of side menu to ","type":"text"},{"type":"codeVoice","code":"destination"},{"text":" view controller.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This method is called when loading from storyboard."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"perform","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"perform"}],"type":"topic","kind":"symbol","url":"\/documentation\/sidemenu\/sidemenusegue\/perform()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"perform"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"perform","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"perform","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","op":"replace","value":"SideMenuController"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"text":"SideMenuController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/title","value":"SideMenuSegue","op":"replace"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/fragments","value":[{"text":"SideMenuSegue","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue~1perform()\/title","value":"perform"},{"value":[{"kind":"text","text":"- "},{"text":"perform","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue~1perform()\/fragments","op":"replace"}]}]}