{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childForStatusBarHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sidemenu\/sidemenucontroller\/childforstatusbarhidden"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sidemenu\/sidemenucontroller\/childforstatusbarhidden"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/childForStatusBarHidden","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childForStatusBarHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"title":"childForStatusBarHidden","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SideMenu@objc(cs)SideMenuController(py)childViewControllerForStatusBarHidden","modules":[{"name":"SideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"childViewControllerForStatusBarHidden"}]},"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"]]},"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/childForStatusBarHidden":{"role":"symbol","title":"childForStatusBarHidden","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childForStatusBarHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/childForStatusBarHidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"childViewControllerForStatusBarHidden"}],"url":"\/documentation\/sidemenu\/sidemenucontroller\/childforstatusbarhidden"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"role":"symbol","title":"SideMenuController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideMenuController"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SideMenuController"}],"url":"\/documentation\/sidemenu\/sidemenucontroller"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"role":"collection","title":"SideMenu","abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","kind":"symbol","type":"topic","url":"\/documentation\/sidemenu"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"childViewControllerForStatusBarHidden"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"childViewControllerForStatusBarHidden"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" * "},{"kind":"identifier","text":"childViewControllerForStatusBarHidden"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1childForStatusBarHidden\/title","value":"childViewControllerForStatusBarHidden"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1childForStatusBarHidden\/fragments","value":[{"kind":"identifier","text":"childViewControllerForStatusBarHidden"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","value":"SideMenuController"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"kind":"identifier","text":"SideMenuController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}