{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"childForStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/childForStatusBarStyle","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"]]},"metadata":{"externalID":"c:@M@SideMenu@objc(cs)SideMenuController(py)childViewControllerForStatusBarStyle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"childForStatusBarStyle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"childViewControllerForStatusBarStyle"}],"title":"childForStatusBarStyle","modules":[{"name":"SideMenu"}],"symbolKind":"property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/sidemenucontroller\/childforstatusbarstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sidemenu\/sidemenucontroller\/childforstatusbarstyle"]}],"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/childForStatusBarStyle":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"childForStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/childForStatusBarStyle","title":"childForStatusBarStyle","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"childViewControllerForStatusBarStyle"}],"url":"\/documentation\/sidemenu\/sidemenucontroller\/childforstatusbarstyle","type":"topic"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"title":"SideMenuController","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","url":"\/documentation\/sidemenu\/sidemenucontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SideMenuController","kind":"identifier"}],"navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"type":"topic","kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"type":"topic","title":"SideMenu","abstract":[],"url":"\/documentation\/sidemenu","role":"collection","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"childViewControllerForStatusBarStyle","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"childViewControllerForStatusBarStyle","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"childViewControllerForStatusBarStyle"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"childViewControllerForStatusBarStyle","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1childForStatusBarStyle\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1childForStatusBarStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"childViewControllerForStatusBarStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","value":"SideMenuController"},{"op":"replace","value":[{"text":"SideMenuController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments"}]}]}