{"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"]]},"kind":"symbol","abstract":[{"type":"text","text":"The identifier of content view controller segue."},{"text":" ","type":"text"},{"type":"text","text":"If the SideMenuController instance is initiated from IB, this identifier will"},{"type":"text","text":" "},{"text":"be used to retrieve the content view controller.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/sidemenucontroller\/contentsegueid"]},{"paths":["\/documentation\/sidemenu\/sidemenucontroller\/contentsegueid"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","modules":[{"name":"SideMenu"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentSegueID"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@SideMenu@objc(cs)SideMenuController(py)contentSegueID","title":"contentSegueID","navigatorTitle":[{"text":"contentSegueID","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@IBInspectable","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"contentSegueID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/contentSegueID","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"url":"\/documentation\/sidemenu\/sidemenucontroller","type":"topic","title":"SideMenuController","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SideMenuController"}],"navigatorTitle":[{"kind":"identifier","text":"SideMenuController"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/contentSegueID":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/contentsegueid","navigatorTitle":[{"kind":"identifier","text":"contentSegueID"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/contentSegueID","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The identifier of content view controller segue."},{"type":"text","text":" "},{"type":"text","text":"If the SideMenuController instance is initiated from IB, this identifier will"},{"text":" ","type":"text"},{"text":"be used to retrieve the content view controller.","type":"text"}],"title":"contentSegueID","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentSegueID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"url":"\/documentation\/sidemenu","kind":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","type":"topic","title":"SideMenu","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"contentSegueID"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"contentSegueID","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"contentSegueID","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SideMenuController","op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SideMenuController"}]},{"value":"contentSegueID","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1contentSegueID\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1contentSegueID\/fragments","value":[{"text":"contentSegueID","kind":"identifier"}],"op":"replace"}]}]}