{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIGestureRecognizerDelegate.gestureRecognizerShouldBegin(_:)"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/gestureRecognizerShouldBegin(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/sidemenu\/sidemenucontroller\/gesturerecognizershouldbegin(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sidemenu\/sidemenucontroller\/gesturerecognizershouldbegin(_:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/UIGestureRecognizerDelegate-Implementations"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"modules":[{"name":"SideMenu"}],"externalID":"c:@CM@SideMenu@objc(cs)SideMenuController(im)gestureRecognizerShouldBegin:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"gestureRecognizerShouldBegin","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"symbolKind":"method","role":"symbol","title":"gestureRecognizerShouldBegin(_:)"},"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/UIGestureRecognizerDelegate-Implementations":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/uigesturerecognizerdelegate-implementations","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/UIGestureRecognizerDelegate-Implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"title":"UIGestureRecognizerDelegate Implementations"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"url":"\/documentation\/sidemenu","kind":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","type":"topic","title":"SideMenu","role":"collection","abstract":[]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/gestureRecognizerShouldBegin(_:)":{"abstract":[],"role":"symbol","type":"topic","title":"gestureRecognizerShouldBegin(_:)","kind":"symbol","navigatorTitle":[{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"url":"\/documentation\/sidemenu\/sidemenucontroller\/gesturerecognizershouldbegin(_:)","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/gestureRecognizerShouldBegin(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizerShouldBegin","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"url":"\/documentation\/sidemenu\/sidemenucontroller","type":"topic","title":"SideMenuController","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SideMenuController"}],"navigatorTitle":[{"kind":"identifier","text":"SideMenuController"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"gestureRecognizerShouldBegin:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"gestureRecognizerShouldBegin:","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1gestureRecognizerShouldBegin(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1gestureRecognizerShouldBegin(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}]},{"op":"replace","value":"SideMenuController","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"text":"SideMenuController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}