{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/sidemenucontroller\/gesturerecognizer(_:shouldreceive:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sidemenu\/sidemenucontroller\/gesturerecognizer(_:shouldreceive:)"]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@CM@SideMenu@objc(cs)SideMenuController(im)gestureRecognizer:shouldReceiveTouch:","title":"gestureRecognizer(_:shouldReceive:)","navigatorTitle":[{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}],"modules":[{"name":"SideMenu"}],"extendedModule":"SideMenu","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":": "},{"text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/UIGestureRecognizerDelegate-Implementations"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"gestureRecognizer","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":", ","kind":"text"},{"text":"shouldReceive","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"touch"},{"text":": ","kind":"text"},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/gestureRecognizer(_:shouldReceive:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIGestureRecognizerDelegate.gestureRecognizer(_:shouldReceive:)"},{"type":"text","text":"."}],"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"url":"\/documentation\/sidemenu\/sidemenucontroller","type":"topic","title":"SideMenuController","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SideMenuController"}],"navigatorTitle":[{"kind":"identifier","text":"SideMenuController"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/UIGestureRecognizerDelegate-Implementations":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/uigesturerecognizerdelegate-implementations","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/UIGestureRecognizerDelegate-Implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"title":"UIGestureRecognizerDelegate Implementations"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/gestureRecognizer(_:shouldReceive:)":{"abstract":[],"role":"symbol","type":"topic","title":"gestureRecognizer(_:shouldReceive:)","kind":"symbol","navigatorTitle":[{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}],"url":"\/documentation\/sidemenu\/sidemenucontroller\/gesturerecognizer(_:shouldreceive:)","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/gestureRecognizer(_:shouldReceive:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"url":"\/documentation\/sidemenu","kind":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","type":"topic","title":"SideMenu","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"gestureRecognizer:shouldReceiveTouch:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"gestureRecognizer:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"gestureRecognizer"},{"text":" ","kind":"text"},{"text":"shouldReceiveTouch:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"touch"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","value":"SideMenuController"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"kind":"identifier","text":"SideMenuController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1gestureRecognizer(_:shouldReceive:)\/title","value":"gestureRecognizer:shouldReceiveTouch:"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1gestureRecognizer(_:shouldReceive:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}]}]}]}