{"sections":[],"abstract":[{"type":"text","text":"The identifier of menu view controller segue."},{"type":"text","text":" "},{"text":"If the SideMenuController instance is initiated from IB, this identifier will","type":"text"},{"type":"text","text":" "},{"text":"be used to retrieve the menu view controller.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"menuSegueID"}],"symbolKind":"property","modules":[{"name":"SideMenu"}],"externalID":"c:@M@SideMenu@objc(cs)SideMenuController(py)menuSegueID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"menuSegueID","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","roleHeading":"Instance Property","title":"menuSegueID"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@IBInspectable","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"menuSegueID"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/menuSegueID"},"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/sidemenucontroller\/menusegueid"]},{"paths":["\/documentation\/sidemenu\/sidemenucontroller\/menusegueid"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu":{"abstract":[],"url":"\/documentation\/sidemenu","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","type":"topic","kind":"symbol","title":"SideMenu","role":"collection"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"url":"\/documentation\/sidemenu\/sidemenucontroller","role":"symbol","title":"SideMenuController","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SideMenuController"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/menuSegueID":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"menuSegueID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","title":"menuSegueID","kind":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/menuSegueID","type":"topic","abstract":[{"type":"text","text":"The identifier of menu view controller segue."},{"text":" ","type":"text"},{"type":"text","text":"If the SideMenuController instance is initiated from IB, this identifier will"},{"text":" ","type":"text"},{"type":"text","text":"be used to retrieve the menu view controller."}],"url":"\/documentation\/sidemenu\/sidemenucontroller\/menusegueid","navigatorTitle":[{"text":"menuSegueID","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"menuSegueID"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"menuSegueID","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"menuSegueID","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","value":"SideMenuController"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"text":"SideMenuController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1menuSegueID\/title","value":"menuSegueID","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"menuSegueID"}],"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1menuSegueID\/fragments"}]}]}