{"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prepare","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIStoryboardSegue","kind":"typeIdentifier","text":"UIStoryboardSegue"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"title":"prepare(for:sender:)","externalID":"c:@M@SideMenu@objc(cs)SideMenuController(im)prepareForSegue:sender:","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"prepareForSegue:sender:","kind":"identifier"}],"modules":[{"name":"SideMenu"}],"roleHeading":"Instance Method"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/sidemenucontroller\/prepare(for:sender:)"]},{"paths":["\/documentation\/sidemenu\/sidemenucontroller\/prepare(for:sender:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"]]},"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/prepare(for:sender:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"segue","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIStoryboardSegue","text":"UIStoryboardSegue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sender"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}]}]}],"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu":{"abstract":[],"url":"\/documentation\/sidemenu","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","type":"topic","kind":"symbol","title":"SideMenu","role":"collection"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"url":"\/documentation\/sidemenu\/sidemenucontroller","role":"symbol","title":"SideMenuController","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SideMenuController"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/prepare(for:sender:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prepare","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"UIStoryboardSegue","preciseIdentifier":"c:objc(cs)UIStoryboardSegue","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sender","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"role":"symbol","title":"prepare(for:sender:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/prepare(for:sender:)","type":"topic","url":"\/documentation\/sidemenu\/sidemenucontroller\/prepare(for:sender:)","navigatorTitle":[{"text":"prepareForSegue:sender:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"prepareForSegue:sender:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"prepareForSegue:sender:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"prepareForSegue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIStoryboardSegue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIStoryboardSegue"},{"kind":"text","text":" *) "},{"text":"segue","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sender:"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sender"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","op":"replace","value":"SideMenuController"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"text":"SideMenuController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1prepare(for:sender:)\/title","value":"prepareForSegue:sender:"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1prepare(for:sender:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"prepareForSegue:sender:","kind":"identifier"}],"op":"replace"}]}]}