{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/sidemenucontroller\/shouldautorotate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sidemenu\/sidemenucontroller\/shouldautorotate"]}],"metadata":{"title":"shouldAutorotate","role":"symbol","externalID":"c:@M@SideMenu@objc(cs)SideMenuController(py)shouldAutorotate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldAutorotate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"SideMenu"}],"symbolKind":"property","navigatorTitle":[{"text":"shouldAutorotate","kind":"identifier"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shouldAutorotate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/shouldAutorotate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/shouldAutorotate":{"abstract":[],"type":"topic","title":"shouldAutorotate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shouldAutorotate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"shouldAutorotate","kind":"identifier"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/shouldAutorotate","kind":"symbol","role":"symbol","url":"\/documentation\/sidemenu\/sidemenucontroller\/shouldautorotate"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"title":"SideMenuController","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","url":"\/documentation\/sidemenu\/sidemenucontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SideMenuController","kind":"identifier"}],"navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"type":"topic","kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"type":"topic","title":"SideMenu","abstract":[],"url":"\/documentation\/sidemenu","role":"collection","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"shouldAutorotate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"shouldAutorotate"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"shouldAutorotate","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"shouldAutorotate","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1shouldAutorotate\/title"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1shouldAutorotate\/fragments","value":[{"text":"shouldAutorotate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","op":"replace","value":"SideMenuController"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","op":"replace","value":[{"text":"SideMenuController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}