{"sections":[],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/supportedInterfaceOrientations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@SideMenu@objc(cs)SideMenuController(py)supportedInterfaceOrientations","navigatorTitle":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"supportedInterfaceOrientations","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIInterfaceOrientationMask","text":"UIInterfaceOrientationMask","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"SideMenu"}],"title":"supportedInterfaceOrientations","roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedInterfaceOrientations"},{"text":": ","kind":"text"},{"text":"UIInterfaceOrientationMask","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/sidemenucontroller\/supportedinterfaceorientations"]},{"paths":["\/documentation\/sidemenu\/sidemenucontroller\/supportedinterfaceorientations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"]]},"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/supportedInterfaceOrientations":{"role":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/supportedInterfaceOrientations","url":"\/documentation\/sidemenu\/sidemenucontroller\/supportedinterfaceorientations","kind":"symbol","type":"topic","navigatorTitle":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"supportedInterfaceOrientations","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIInterfaceOrientationMask","text":"UIInterfaceOrientationMask","kind":"typeIdentifier"}],"title":"supportedInterfaceOrientations"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"role":"collection","url":"\/documentation\/sidemenu","kind":"symbol","title":"SideMenu","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","abstract":[],"type":"topic"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"title":"SideMenuController","role":"symbol","abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"type":"topic","navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideMenuController"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","url":"\/documentation\/sidemenu\/sidemenucontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"supportedInterfaceOrientations","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@E@UIInterfaceOrientationMask","text":"UIInterfaceOrientationMask","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportedInterfaceOrientations"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1supportedInterfaceOrientations\/title","op":"replace","value":"supportedInterfaceOrientations"},{"value":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1supportedInterfaceOrientations\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","value":"SideMenuController"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"kind":"identifier","text":"SideMenuController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}