{"variants":[{"paths":["\/documentation\/sidemenu\/sidemenucontroller\/uigesturerecognizerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sidemenu\/sidemenucontroller\/uigesturerecognizerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/UIGestureRecognizerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/gestureRecognizer(_:shouldReceive:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/gestureRecognizerShouldBegin(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SideMenu"}],"role":"collectionGroup","title":"UIGestureRecognizerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"]]},"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu":{"role":"collection","title":"SideMenu","abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","kind":"symbol","type":"topic","url":"\/documentation\/sidemenu"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/gestureRecognizer(_:shouldReceive:)":{"role":"symbol","title":"gestureRecognizer(_:shouldReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/gestureRecognizer(_:shouldReceive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"url":"\/documentation\/sidemenu\/sidemenucontroller\/gesturerecognizer(_:shouldreceive:)"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/gestureRecognizerShouldBegin(_:)":{"role":"symbol","title":"gestureRecognizerShouldBegin(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/gestureRecognizerShouldBegin(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"url":"\/documentation\/sidemenu\/sidemenucontroller\/gesturerecognizershouldbegin(_:)"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"role":"symbol","title":"SideMenuController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideMenuController"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SideMenuController"}],"url":"\/documentation\/sidemenu\/sidemenucontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/gestureRecognizer(_:shouldReceive:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/gestureRecognizerShouldBegin(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1gestureRecognizer(_:shouldReceive:)\/title","value":"gestureRecognizer:shouldReceiveTouch:"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1gestureRecognizer(_:shouldReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1gestureRecognizerShouldBegin(_:)\/title","value":"gestureRecognizerShouldBegin:"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1gestureRecognizerShouldBegin(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","value":"SideMenuController"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"kind":"identifier","text":"SideMenuController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}