{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animateTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":" "},{"kind":"internalParam","text":"transitionContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sidemenu\/basictransitionanimator\/animatetransition(using:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sidemenu\/basictransitionanimator\/animatetransition(using:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/animateTransition(using:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIViewControllerAnimatedTransitioning.animateTransition(using:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animateTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"title":"animateTransition(using:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SideMenu@objc(cs)BasicTransitionAnimator(im)animateTransition:","modules":[{"name":"SideMenu"}],"navigatorTitle":[{"kind":"identifier","text":"animateTransition:"}]},"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator"]]},"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/BasicTransitionAnimator":{"role":"symbol","title":"BasicTransitionAnimator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasicTransitionAnimator"}],"abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BasicTransitionAnimator"}],"url":"\/documentation\/sidemenu\/basictransitionanimator"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"role":"collection","title":"SideMenu","abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","kind":"symbol","type":"topic","url":"\/documentation\/sidemenu"},"doc://com.kukushi.SideMenu/documentation/SideMenu/BasicTransitionAnimator/animateTransition(using:)":{"role":"symbol","title":"animateTransition(using:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animateTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/animateTransition(using:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animateTransition:"}],"url":"\/documentation\/sidemenu\/basictransitionanimator\/animatetransition(using:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"animateTransition:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animateTransition:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"animateTransition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UIViewControllerContextTransitioning>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"transitionContext"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator\/title","value":"BasicTransitionAnimator"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator\/fragments","value":[{"kind":"identifier","text":"BasicTransitionAnimator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator~1animateTransition(using:)\/title","value":"animateTransition:"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator~1animateTransition(using:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animateTransition:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}