{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator"]]},"kind":"symbol","metadata":{"externalID":"c:@M@SideMenu@objc(cs)BasicTransitionAnimator(im)transitionDuration:","role":"symbol","modules":[{"name":"SideMenu"}],"roleHeading":"Instance Method","title":"transitionDuration(using:)","symbolKind":"method","navigatorTitle":[{"text":"transitionDuration:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionDuration"},{"kind":"text","text":"("},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}]},"sections":[],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/transitionDuration(using:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionDuration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"transitionContext","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","text":"UIViewControllerContextTransitioning"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/sidemenu\/basictransitionanimator\/transitionduration(using:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sidemenu\/basictransitionanimator\/transitionduration(using:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIViewControllerAnimatedTransitioning.transitionDuration(using:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/BasicTransitionAnimator/transitionDuration(using:)":{"role":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/transitionDuration(using:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"transitionDuration:"}],"url":"\/documentation\/sidemenu\/basictransitionanimator\/transitionduration(using:)","abstract":[],"title":"transitionDuration(using:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"transitionDuration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerContextTransitioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"text":"?) -> ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"type":"topic"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"type":"topic","title":"SideMenu","abstract":[],"url":"\/documentation\/sidemenu","role":"collection","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/BasicTransitionAnimator":{"title":"BasicTransitionAnimator","url":"\/documentation\/sidemenu\/basictransitionanimator","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BasicTransitionAnimator"}],"kind":"symbol","navigatorTitle":[{"text":"BasicTransitionAnimator","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"transitionDuration:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"transitionDuration:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"transitionDuration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<UIViewControllerContextTransitioning>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerContextTransitioning","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"transitionContext","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"transitionDuration:","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator~1transitionDuration(using:)\/title"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator~1transitionDuration(using:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"transitionDuration:","kind":"identifier"}],"op":"replace"},{"value":"BasicTransitionAnimator","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator\/fragments","value":[{"text":"BasicTransitionAnimator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}