# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generates documentation for given version."
  lane :doc do |options| 
    Actions.sh('cd .. && xcodebuild docbuild -scheme SideMenu -destination generic/platform=iOS OTHER_DOCC_FLAGS="--transform-for-static-hosting --hosting-base-path SideMenu --output-path docs docs"')
  end

  desc "Runs all the tests"
  lane :test do

    scan(
      scheme: "SideMenu", 
      devices: ['iPhone Xʀ']
      )
  end
end
