{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"variants":[{"paths":["\/documentation\/sidemenu"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sidemenu"]}],"metadata":{"roleHeading":"Framework","symbolKind":"module","role":"collection","title":"SideMenu","modules":[{"name":"SideMenu"}],"externalID":"SideMenu"},"kind":"symbol","topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue"]},{"identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuControllerDelegate"],"title":"Protocols"},{"identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/UIKit"],"title":"Extended Modules"}],"sections":[],"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu":{"type":"topic","title":"SideMenu","abstract":[],"url":"\/documentation\/sidemenu","role":"collection","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/UIKit":{"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/UIKit","role":"collection","url":"\/documentation\/sidemenu\/uikit","title":"UIKit","type":"topic","abstract":[],"kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuVersionNumber":{"abstract":[{"text":"Project version number for SideMenu.","type":"text"}],"url":"\/documentation\/sidemenu\/sidemenuversionnumber","fragments":[{"kind":"identifier","text":"SideMenuVersionNumber"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuVersionNumber","kind":"symbol","title":"SideMenuVersionNumber"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"title":"SideMenuController","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","url":"\/documentation\/sidemenu\/sidemenucontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SideMenuController","kind":"identifier"}],"navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"type":"topic","kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/BasicTransitionAnimator":{"title":"BasicTransitionAnimator","url":"\/documentation\/sidemenu\/basictransitionanimator","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BasicTransitionAnimator"}],"kind":"symbol","navigatorTitle":[{"text":"BasicTransitionAnimator","kind":"identifier"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuVersionString":{"url":"\/documentation\/sidemenu\/sidemenuversionstring","kind":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuVersionString","fragments":[{"text":"SideMenuVersionString","kind":"identifier"}],"title":"SideMenuVersionString","role":"symbol","abstract":[{"type":"text","text":"Project version string for SideMenu."}],"type":"topic"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuControllerDelegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SideMenuControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuControllerDelegate","abstract":[],"url":"\/documentation\/sidemenu\/sidemenucontrollerdelegate","type":"topic","title":"SideMenuControllerDelegate","kind":"symbol","navigatorTitle":[{"text":"SideMenuControllerDelegate","kind":"identifier"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue":{"type":"topic","kind":"symbol","abstract":[{"text":"Custom Segue that is required for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"},{"text":" to be used in Storyboard.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SideMenuSegue","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SideMenuSegue"}],"url":"\/documentation\/sidemenu\/sidemenusegue","title":"SideMenuSegue","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Classes","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue"]},{"title":"Variables","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuVersionNumber","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"SideMenuController","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","op":"replace"},{"value":[{"text":"SideMenuController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator\/title","value":"BasicTransitionAnimator","op":"replace"},{"value":[{"kind":"identifier","text":"BasicTransitionAnimator"}],"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator\/fragments"},{"value":"SideMenuSegue","op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/title"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/fragments","value":[{"kind":"identifier","text":"SideMenuSegue"}],"op":"replace"}]}]}