{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/content"]}],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/content","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum"]]},"sections":[],"metadata":{"title":"SideMenuSegue.ContentType.content","modules":[{"name":"SideMenu"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","externalID":"s:8SideMenu0aB5SegueC11ContentTypeO7contentyA2EmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"content"}]},"abstract":[{"text":"represent the content scene of side menu","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"content","kind":"identifier"}]}]}],"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu":{"abstract":[],"url":"\/documentation\/sidemenu","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","type":"topic","kind":"symbol","title":"SideMenu","role":"collection"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SideMenuSegue","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SideMenuSegue"}],"abstract":[{"text":"Custom Segue that is required for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"},{"text":" to be used in Storyboard.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","title":"SideMenuSegue","url":"\/documentation\/sidemenu\/sidemenusegue"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum":{"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContentType"}],"navigatorTitle":[{"text":"ContentType","kind":"identifier"}],"abstract":[{"text":"The type of segue","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum","title":"SideMenuSegue.ContentType","url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"url":"\/documentation\/sidemenu\/sidemenucontroller","role":"symbol","title":"SideMenuController","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SideMenuController"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum/content":{"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"content","kind":"identifier"}],"abstract":[{"text":"represent the content scene of side menu","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/content","title":"SideMenuSegue.ContentType.content","url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/content"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/title","op":"replace","value":"SideMenuSegue"},{"value":[{"text":"SideMenuSegue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/fragments"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","value":"SideMenuController","op":"replace"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SideMenuController"}]}]}]}