{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/equatable-implementations"]}],"metadata":{"role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"SideMenu"}]},"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/!=(_:_:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum"]]},"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/!=(_:_:)","kind":"symbol","abstract":[],"url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/!=(_:_:)","title":"!=(_:_:)","role":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"role":"collection","url":"\/documentation\/sidemenu","kind":"symbol","title":"SideMenu","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","abstract":[],"type":"topic"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum":{"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum","navigatorTitle":[{"kind":"identifier","text":"ContentType"}],"role":"symbol","title":"SideMenuSegue.ContentType","abstract":[{"type":"text","text":"The type of segue"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContentType"}],"type":"topic","url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum","kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue":{"abstract":[{"text":"Custom Segue that is required for ","type":"text"},{"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","type":"reference","isActive":true},{"type":"text","text":" to be used in Storyboard."}],"role":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SideMenuSegue","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sidemenu\/sidemenusegue","title":"SideMenuSegue","type":"topic","navigatorTitle":[{"text":"SideMenuSegue","kind":"identifier"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"title":"SideMenuController","role":"symbol","abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"type":"topic","navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideMenuController"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","url":"\/documentation\/sidemenu\/sidemenucontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SideMenuSegue","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/fragments","value":[{"text":"SideMenuSegue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","value":"SideMenuController"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"text":"SideMenuController","kind":"identifier"}],"op":"replace"}]}]}