{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/hash(into:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"hash(into:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::s:8SideMenu0aB5SegueC11ContentTypeO","extendedModule":"Swift","modules":[{"name":"SideMenu"}]},"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/RawRepresentable-Implementations"]]},"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum/hash(into:)":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/hash(into:)","kind":"symbol","type":"topic","url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/hash(into:)"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum":{"role":"symbol","title":"SideMenuSegue.ContentType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentType"}],"abstract":[{"type":"text","text":"The type of segue"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContentType"}],"url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/rawrepresentable-implementations"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"role":"symbol","title":"SideMenuController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideMenuController"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SideMenuController"}],"url":"\/documentation\/sidemenu\/sidemenucontroller"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"role":"collection","title":"SideMenu","abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","kind":"symbol","type":"topic","url":"\/documentation\/sidemenu"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue":{"role":"symbol","title":"SideMenuSegue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideMenuSegue"}],"abstract":[{"type":"text","text":"Custom Segue that is required for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"},{"type":"text","text":" to be used in Storyboard."}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SideMenuSegue"}],"url":"\/documentation\/sidemenu\/sidemenusegue"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","value":"SideMenuController"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"kind":"identifier","text":"SideMenuController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/title","value":"SideMenuSegue"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/fragments","value":[{"kind":"identifier","text":"SideMenuSegue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}