{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"menu"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/menu"},"metadata":{"modules":[{"name":"SideMenu"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"menu"}],"roleHeading":"Case","role":"symbol","title":"SideMenuSegue.ContentType.menu","externalID":"s:8SideMenu0aB5SegueC11ContentTypeO4menuyA2EmF"},"sections":[],"abstract":[{"type":"text","text":"represent the menu scene of side menu"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/menu"]}],"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum"]]},"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu":{"role":"collection","url":"\/documentation\/sidemenu","kind":"symbol","title":"SideMenu","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","abstract":[],"type":"topic"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue":{"abstract":[{"text":"Custom Segue that is required for ","type":"text"},{"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","type":"reference","isActive":true},{"type":"text","text":" to be used in Storyboard."}],"role":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SideMenuSegue","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sidemenu\/sidemenusegue","title":"SideMenuSegue","type":"topic","navigatorTitle":[{"text":"SideMenuSegue","kind":"identifier"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum/menu":{"url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/menu","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/menu","role":"symbol","abstract":[{"type":"text","text":"represent the menu scene of side menu"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"menu","kind":"identifier"}],"kind":"symbol","type":"topic","title":"SideMenuSegue.ContentType.menu"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum":{"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum","navigatorTitle":[{"kind":"identifier","text":"ContentType"}],"role":"symbol","title":"SideMenuSegue.ContentType","abstract":[{"type":"text","text":"The type of segue"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContentType"}],"type":"topic","url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum","kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"title":"SideMenuController","role":"symbol","abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"type":"topic","navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideMenuController"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","url":"\/documentation\/sidemenu\/sidemenucontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/title","value":"SideMenuSegue"},{"op":"replace","value":[{"kind":"identifier","text":"SideMenuSegue"}],"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/fragments"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","op":"replace","value":"SideMenuController"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"kind":"identifier","text":"SideMenuController"}],"op":"replace"}]}]}