{"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/hashValue"]},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/hash(into:)"]}],"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum"]]},"metadata":{"title":"RawRepresentable Implementations","modules":[{"name":"SideMenu"}],"role":"collectionGroup"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/RawRepresentable-Implementations"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/rawrepresentable-implementations"]}],"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue":{"type":"topic","kind":"symbol","abstract":[{"text":"Custom Segue that is required for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"},{"text":" to be used in Storyboard.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SideMenuSegue","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SideMenuSegue"}],"url":"\/documentation\/sidemenu\/sidemenusegue","title":"SideMenuSegue","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","role":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"title":"SideMenuController","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","url":"\/documentation\/sidemenu\/sidemenucontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SideMenuController","kind":"identifier"}],"navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"type":"topic","kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum/hash(into:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"type":"topic","title":"hash(into:)","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/hash(into:)","url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/hash(into:)","kind":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"abstract":[],"role":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum/hashValue":{"url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum\/hashvalue","abstract":[],"kind":"symbol","role":"symbol","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"title":"hashValue","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum\/hashValue","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum":{"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum","abstract":[{"type":"text","text":"The type of segue"}],"title":"SideMenuSegue.ContentType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ContentType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ContentType"}],"kind":"symbol","type":"topic","url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"type":"topic","title":"SideMenu","abstract":[],"url":"\/documentation\/sidemenu","role":"collection","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SideMenuSegue","op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/title"},{"op":"replace","value":[{"text":"SideMenuSegue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title","value":"SideMenuController"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"text":"SideMenuController","kind":"identifier"}],"op":"replace"}]}]}