{"relationshipsSections":[{"identifiers":["doc:\/\/com.kukushi.SideMenu\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.kukushi.SideMenu\/objc(pl)NSObject","doc:\/\/com.kukushi.SideMenu\/s7CVarArgP","doc:\/\/com.kukushi.SideMenu\/s28CustomDebugStringConvertibleP","doc:\/\/com.kukushi.SideMenu\/s23CustomStringConvertibleP","doc:\/\/com.kukushi.SideMenu\/SQ","doc:\/\/com.kukushi.SideMenu\/SH","doc:\/\/com.kukushi.SideMenu\/objc(pl)UIViewControllerAnimatedTransitioning"],"kind":"relationships","type":"conformsTo"}],"metadata":{"externalID":"c:@M@SideMenu@objc(cs)BasicTransitionAnimator","roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BasicTransitionAnimator","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"SideMenu"}],"title":"BasicTransitionAnimator","navigatorTitle":[{"kind":"identifier","text":"BasicTransitionAnimator"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sidemenu\/basictransitionanimator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sidemenu\/basictransitionanimator"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BasicTransitionAnimator","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu"]]},"sections":[],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/init(options:duration:)"]},{"identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/animateTransition(using:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/transitionDuration(using:)"],"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/BasicTransitionAnimator":{"url":"\/documentation\/sidemenu\/basictransitionanimator","navigatorTitle":[{"kind":"identifier","text":"BasicTransitionAnimator"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator","kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"BasicTransitionAnimator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BasicTransitionAnimator","kind":"identifier"}]},"doc://com.kukushi.SideMenu/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.kukushi.SideMenu\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.kukushi.SideMenu/s7CVarArgP":{"identifier":"doc:\/\/com.kukushi.SideMenu\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.kukushi.SideMenu/SH":{"identifier":"doc:\/\/com.kukushi.SideMenu\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.kukushi.SideMenu/documentation/SideMenu/BasicTransitionAnimator/transitionDuration(using:)":{"url":"\/documentation\/sidemenu\/basictransitionanimator\/transitionduration(using:)","navigatorTitle":[{"kind":"identifier","text":"transitionDuration:"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/transitionDuration(using:)","kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"transitionDuration(using:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionDuration"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"using"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/BasicTransitionAnimator/init(options:duration:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIViewAnimationOptions","text":"AnimationOptions"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/sidemenu\/basictransitionanimator\/init(options:duration:)","type":"topic","abstract":[{"text":"Initialize a new animator with animation options and duration.","type":"text"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/init(options:duration:)","title":"init(options:duration:)"},"doc://com.kukushi.SideMenu/objc(cs)NSObject":{"identifier":"doc:\/\/com.kukushi.SideMenu\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.kukushi.SideMenu/SQ":{"identifier":"doc:\/\/com.kukushi.SideMenu\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.kukushi.SideMenu/objc(pl)UIViewControllerAnimatedTransitioning":{"identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)UIViewControllerAnimatedTransitioning","type":"unresolvable","title":"UIViewControllerAnimatedTransitioning"},"doc://com.kukushi.SideMenu/documentation/SideMenu/BasicTransitionAnimator/animateTransition(using:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animateTransition"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"using"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","text":"UIViewControllerContextTransitioning"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/sidemenu\/basictransitionanimator\/animatetransition(using:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/animateTransition(using:)","title":"animateTransition(using:)","navigatorTitle":[{"kind":"identifier","text":"animateTransition:"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"url":"\/documentation\/sidemenu","kind":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","type":"topic","title":"SideMenu","role":"collection","abstract":[]},"doc://com.kukushi.SideMenu/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)NSObject","type":"unresolvable"},"doc://com.kukushi.SideMenu/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.kukushi.SideMenu\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"BasicTransitionAnimator","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"BasicTransitionAnimator","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"BasicTransitionAnimator","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/animateTransition(using:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/BasicTransitionAnimator\/transitionDuration(using:)"],"title":"Instance Methods"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.kukushi.SideMenu\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.kukushi.SideMenu\/objc(pl)UIViewControllerAnimatedTransitioning"],"kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasicTransitionAnimator"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator\/title","value":"BasicTransitionAnimator","op":"replace"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator\/fragments","value":[{"kind":"identifier","text":"BasicTransitionAnimator"}],"op":"replace"},{"value":"transitionDuration:","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator~1transitionDuration(using:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"transitionDuration:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator~1transitionDuration(using:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator~1animateTransition(using:)\/title","op":"replace","value":"animateTransition:"},{"value":[{"kind":"text","text":"- "},{"text":"animateTransition:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1BasicTransitionAnimator~1animateTransition(using:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}