{"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SideMenuController","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"inlineContent":[{"type":"text","text":"The overall architecture of SideMenuController is:"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"SideMenuController"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"├── Menu View Controller"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"└── Content View Controller","type":"text"}]}],"kind":"content"}],"topicSections":[{"title":"Structures","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/Preferences-swift.struct"]},{"title":"Initializers","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/init(contentViewController:menuViewController:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/childForStatusBarHidden","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/childForStatusBarStyle","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/contentSegueID","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/contentViewController","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/delegate","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/isMenuRevealed","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/menuSegueID","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/menuViewController","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/shouldAutorotate","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/supportedInterfaceOrientations"]},{"identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/cache(viewController:with:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/cache(viewControllerGenerator:with:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/clearCache(with:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/currentCacheIdentifier()","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/hideMenu(animated:completion:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/prepare(for:sender:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/revealMenu(animated:completion:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/setContentViewController(to:animated:completion:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/setContentViewController(with:animated:completion:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/viewDidLoad()","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/viewWillTransition(to:with:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/preferences-swift.type.property"],"title":"Type Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/UIGestureRecognizerDelegate-Implementations"],"generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SideMenuController"}],"role":"symbol","symbolKind":"class","modules":[{"name":"SideMenu"}],"title":"SideMenuController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SideMenuController","kind":"identifier"}],"externalID":"c:@M@SideMenu@objc(cs)SideMenuController","roleHeading":"Class"},"kind":"symbol","variants":[{"paths":["\/documentation\/sidemenu\/sidemenucontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sidemenu\/sidemenucontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"},"relationshipsSections":[{"identifiers":["doc:\/\/com.kukushi.SideMenu\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.kukushi.SideMenu\/objc(pl)NSCoding","doc:\/\/com.kukushi.SideMenu\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.kukushi.SideMenu\/objc(pl)NSObject","doc:\/\/com.kukushi.SideMenu\/s7CVarArgP","doc:\/\/com.kukushi.SideMenu\/s28CustomDebugStringConvertibleP","doc:\/\/com.kukushi.SideMenu\/s23CustomStringConvertibleP","doc:\/\/com.kukushi.SideMenu\/SQ","doc:\/\/com.kukushi.SideMenu\/SH","doc:\/\/com.kukushi.SideMenu\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.kukushi.SideMenu\/objc(pl)UIAppearanceContainer","doc:\/\/com.kukushi.SideMenu\/objc(pl)UIContentContainer","doc:\/\/com.kukushi.SideMenu\/objc(pl)UIFocusEnvironment","doc:\/\/com.kukushi.SideMenu\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.kukushi.SideMenu\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.kukushi.SideMenu\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.kukushi.SideMenu\/objc(pl)UIStateRestoring","doc:\/\/com.kukushi.SideMenu\/5UIKit23UITraitChangeObservableP","doc:\/\/com.kukushi.SideMenu\/objc(pl)UITraitEnvironment","doc:\/\/com.kukushi.SideMenu\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/viewWillTransition(to:with:)":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/viewwilltransition(to:with:)","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/viewWillTransition(to:with:)","kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"viewWillTransition(to:with:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillTransition"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.kukushi.SideMenu/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.kukushi.SideMenu\/SH","type":"unresolvable"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/currentCacheIdentifier()":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/currentcacheidentifier()","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/currentCacheIdentifier()","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Return the identifier of current content view controller.","type":"text"}],"title":"currentCacheIdentifier()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentCacheIdentifier","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]},"doc://com.kukushi.SideMenu/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)NSExtensionRequestHandling"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/delegate":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/delegate","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/delegate","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"The side menu controller’s delegate object.","type":"text"}],"title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SideMenuControllerDelegate","preciseIdentifier":"s:8SideMenu0aB18ControllerDelegateP","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.kukushi.SideMenu/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.kukushi.SideMenu\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/clearCache(with:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/sidemenu\/sidemenucontroller\/clearcache(with:)","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/clearCache(with:)","title":"clearCache(with:)","abstract":[{"type":"text","text":"Clears cached view controller or generators with identifier."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearCache"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/supportedInterfaceOrientations":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/supportedinterfaceorientations","navigatorTitle":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/supportedInterfaceOrientations","kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"supportedInterfaceOrientations","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedInterfaceOrientations","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask","text":"UIInterfaceOrientationMask"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"url":"\/documentation\/sidemenu","kind":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","type":"topic","title":"SideMenu","role":"collection","abstract":[]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/preferences-swift.type.property":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/preferences-swift.type.property","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/preferences-swift.type.property","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configure this property to change the behavior of SideMenuController;"}],"title":"preferences","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferences"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SideMenu@objc(cs)SideMenuController","text":"SideMenuController","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:8SideMenu0aB10ControllerC11PreferencesV","text":"Preferences"}]},"doc://com.kukushi.SideMenu/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/contentSegueID":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/contentsegueid","navigatorTitle":[{"kind":"identifier","text":"contentSegueID"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/contentSegueID","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The identifier of content view controller segue."},{"type":"text","text":" "},{"type":"text","text":"If the SideMenuController instance is initiated from IB, this identifier will"},{"text":" ","type":"text"},{"text":"be used to retrieve the content view controller.","type":"text"}],"title":"contentSegueID","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentSegueID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.kukushi.SideMenu/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/cache(viewController:with:)":{"abstract":[{"type":"text","text":"Caches the view controller with identifier."}],"kind":"symbol","type":"topic","title":"cache(viewController:with:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cache"},{"kind":"text","text":"("},{"text":"viewController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"url":"\/documentation\/sidemenu\/sidemenucontroller\/cache(viewcontroller:with:)","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/cache(viewController:with:)"},"doc://com.kukushi.SideMenu/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/revealMenu(animated:completion:)":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/revealmenu(animated:completion:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"revealMenu"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"abstract":[{"type":"text","text":"Reveals the menu."}],"title":"revealMenu(animated:completion:)","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/revealMenu(animated:completion:)"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/setContentViewController(to:animated:completion:)":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/setcontentviewcontroller(to:animated:completion:)","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/setContentViewController(to:animated:completion:)","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Change the content view controller to "},{"code":"viewController","type":"codeVoice"}],"title":"setContentViewController(to:animated:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setContentViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}]},"doc://com.kukushi.SideMenu/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)NSCoding"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/isMenuRevealed":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/ismenurevealed","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/isMenuRevealed","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Return true if the menu is now revealing."}],"title":"isMenuRevealed","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isMenuRevealed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.kukushi.SideMenu/objc(pl)UIGestureRecognizerDelegate":{"identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)UIGestureRecognizerDelegate","type":"unresolvable","title":"UIGestureRecognizerDelegate"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"url":"\/documentation\/sidemenu\/sidemenucontroller","type":"topic","title":"SideMenuController","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SideMenuController"}],"navigatorTitle":[{"kind":"identifier","text":"SideMenuController"}],"abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController"},"doc://com.kukushi.SideMenu/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.kukushi.SideMenu\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.kukushi.SideMenu/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/contentViewController":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/contentviewcontroller","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/contentViewController","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The content view controller. Changes its value will change the display immediately."},{"type":"text","text":" "},{"type":"text","text":"If the new value is already one of the side menu controller’s child controllers, nothing will happen beside value change."},{"text":" ","type":"text"},{"type":"text","text":"If you want a caching approach, use "},{"type":"reference","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/setContentViewController(with:animated:completion:)","isActive":true},{"text":". Its value should not be nil.","type":"text"}],"title":"contentViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"contentViewController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/cache(viewControllerGenerator:with:)":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/cache(viewcontrollergenerator:with:)","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/cache(viewControllerGenerator:with:)","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Caches the closure that generate the view controller with identifier.","type":"text"}],"title":"cache(viewControllerGenerator:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cache","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"viewControllerGenerator"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?, ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.kukushi.SideMenu/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.kukushi.SideMenu\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.kukushi.SideMenu/SQ":{"identifier":"doc:\/\/com.kukushi.SideMenu\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/init(contentViewController:menuViewController:)":{"type":"topic","url":"\/documentation\/sidemenu\/sidemenucontroller\/init(contentviewcontroller:menuviewcontroller:)","title":"init(contentViewController:menuViewController:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/init(contentViewController:menuViewController:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"contentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"menuViewController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Creates a "},{"type":"reference","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","isActive":true},{"type":"text","text":" instance with the content view controller and menu view controller."}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/menuViewController":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/menuviewcontroller","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/menuViewController","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The menu view controller. Its value should not be nil."}],"title":"menuViewController","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"menuViewController","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"!","kind":"text"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/childForStatusBarHidden":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"childForStatusBarHidden"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/childForStatusBarHidden","title":"childForStatusBarHidden","role":"symbol","url":"\/documentation\/sidemenu\/sidemenucontroller\/childforstatusbarhidden","navigatorTitle":[{"kind":"identifier","text":"childViewControllerForStatusBarHidden"}]},"doc://com.kukushi.SideMenu/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/s7CVarArgP"},"doc://com.kukushi.SideMenu/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)UIStateRestoring"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/hideMenu(animated:completion:)":{"abstract":[{"type":"text","text":"Hides the menu."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideMenu"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/hideMenu(animated:completion:)","title":"hideMenu(animated:completion:)","role":"symbol","url":"\/documentation\/sidemenu\/sidemenucontroller\/hidemenu(animated:completion:)"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/childForStatusBarStyle":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/childforstatusbarstyle","navigatorTitle":[{"kind":"identifier","text":"childViewControllerForStatusBarStyle"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/childForStatusBarStyle","kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"childForStatusBarStyle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"childForStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"?","kind":"text"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/setContentViewController(with:animated:completion:)":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/setcontentviewcontroller(with:animated:completion:)","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/setContentViewController(with:animated:completion:)","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Changes the content view controller to the cached one with given "},{"type":"codeVoice","code":"identifier"},{"text":".","type":"text"}],"title":"setContentViewController(with:animated:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setContentViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}]},"doc://com.kukushi.SideMenu/objc(cs)UIViewController":{"identifier":"doc:\/\/com.kukushi.SideMenu\/objc(cs)UIViewController","title":"UIViewController","type":"unresolvable"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/viewDidLoad()":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/viewdidload()","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/viewDidLoad()","kind":"symbol","type":"topic","role":"symbol","abstract":[{"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","isActive":true,"type":"reference"},{"type":"text","text":" may be initialized from Storyboard, thus we shouldn’t load the view in "},{"code":"loadView()","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"As mentioned by Apple, “If you use Interface Builder to create your views and initialize the view controller,","type":"text"},{"text":" ","type":"text"},{"text":"you must not override this method.”","type":"text"}],"title":"viewDidLoad()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}]},"doc://com.kukushi.SideMenu/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.kukushi.SideMenu/objc(pl)NSObject":{"identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/menuSegueID":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/menusegueid","navigatorTitle":[{"kind":"identifier","text":"menuSegueID"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/menuSegueID","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The identifier of menu view controller segue."},{"type":"text","text":" "},{"type":"text","text":"If the SideMenuController instance is initiated from IB, this identifier will"},{"type":"text","text":" "},{"text":"be used to retrieve the menu view controller.","type":"text"}],"title":"menuSegueID","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"menuSegueID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/initWithCoder:":{"kind":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/initWithCoder:","title":"initWithCoder:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","abstract":[],"url":"\/documentation\/sidemenu\/sidemenucontroller\/initwithcoder:"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/shouldAutorotate":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/shouldautorotate","navigatorTitle":[{"text":"shouldAutorotate","kind":"identifier"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/shouldAutorotate","kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"shouldAutorotate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldAutorotate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/initWithNibName:bundle:":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/initwithnibname:bundle:","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/initWithNibName:bundle:","kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"text":"initWithNibName:bundle:","kind":"identifier"}]},"doc://com.kukushi.SideMenu/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/prepare(for:sender:)":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/prepare(for:sender:)","navigatorTitle":[{"kind":"identifier","text":"prepareForSegue:sender:"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/prepare(for:sender:)","kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"prepare(for:sender:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prepare","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIStoryboardSegue","text":"UIStoryboardSegue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}]},"doc://com.kukushi.SideMenu/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.kukushi.SideMenu/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/Preferences-swift.struct":{"navigatorTitle":[{"text":"Preferences","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Preferences","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sidemenu\/sidemenucontroller\/preferences-swift.struct","abstract":[{"type":"text","text":"The preferences of side menu controller."}],"type":"topic","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/Preferences-swift.struct","title":"SideMenuController.Preferences","role":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController/UIGestureRecognizerDelegate-Implementations":{"url":"\/documentation\/sidemenu\/sidemenucontroller\/uigesturerecognizerdelegate-implementations","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/UIGestureRecognizerDelegate-Implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"title":"UIGestureRecognizerDelegate Implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SideMenuController","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"SideMenuController","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"SideMenuController","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/childForStatusBarHidden","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/childForStatusBarStyle","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/contentSegueID","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/menuSegueID","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/shouldAutorotate","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/supportedInterfaceOrientations"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/initWithCoder:","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/initWithNibName:bundle:","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/prepare(for:sender:)","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/viewDidLoad()","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/viewWillTransition(to:with:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController\/UIGestureRecognizerDelegate-Implementations"]}],"op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.kukushi.SideMenu\/objc(cs)UIViewController"]},{"type":"conformsTo","identifiers":["doc:\/\/com.kukushi.SideMenu\/objc(pl)UIGestureRecognizerDelegate"],"kind":"relationships","title":"Conforms To"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SideMenuController","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1viewWillTransition(to:with:)\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1viewWillTransition(to:with:)\/fragments"},{"value":"supportedInterfaceOrientations","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1supportedInterfaceOrientations\/title","op":"replace"},{"op":"replace","value":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1supportedInterfaceOrientations\/fragments"},{"op":"replace","value":"contentSegueID","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1contentSegueID\/title"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1contentSegueID\/fragments","op":"replace","value":[{"text":"contentSegueID","kind":"identifier"}]},{"op":"replace","value":"SideMenuController","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments","value":[{"kind":"identifier","text":"SideMenuController"}]},{"value":"childViewControllerForStatusBarHidden","op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1childForStatusBarHidden\/title"},{"op":"replace","value":[{"kind":"identifier","text":"childViewControllerForStatusBarHidden"}],"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1childForStatusBarHidden\/fragments"},{"value":"childViewControllerForStatusBarStyle","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1childForStatusBarStyle\/title","op":"replace"},{"value":[{"text":"childViewControllerForStatusBarStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1childForStatusBarStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","value":"menuSegueID","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1menuSegueID\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1menuSegueID\/fragments","value":[{"kind":"identifier","text":"menuSegueID"}]},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1shouldAutorotate\/title","value":"shouldAutorotate","op":"replace"},{"op":"replace","value":[{"text":"shouldAutorotate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1shouldAutorotate\/fragments"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1prepare(for:sender:)\/title","value":"prepareForSegue:sender:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"prepareForSegue:sender:"}],"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController~1prepare(for:sender:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}