{"hierarchy":{"paths":[["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/contentType-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/perform()"]},{"title":"Enumerations","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum"]}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.kukushi.SideMenu\/objc(cs)UIStoryboardSegue"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.kukushi.SideMenu\/objc(pl)NSObject","doc:\/\/com.kukushi.SideMenu\/s7CVarArgP","doc:\/\/com.kukushi.SideMenu\/s28CustomDebugStringConvertibleP","doc:\/\/com.kukushi.SideMenu\/s23CustomStringConvertibleP","doc:\/\/com.kukushi.SideMenu\/SQ","doc:\/\/com.kukushi.SideMenu\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SideMenuSegue"}]}]}],"variants":[{"paths":["\/documentation\/sidemenu\/sidemenusegue"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sidemenu\/sidemenusegue"]}],"identifier":{"url":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Custom Segue that is required for "},{"isActive":true,"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","type":"reference"},{"type":"text","text":" to be used in Storyboard."}],"metadata":{"role":"symbol","modules":[{"name":"SideMenu"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SideMenuSegue"}],"externalID":"c:@M@SideMenu@objc(cs)SideMenuSegue","symbolKind":"class","title":"SideMenuSegue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideMenuSegue"}]},"sections":[],"references":{"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuController":{"title":"SideMenuController","role":"symbol","abstract":[{"type":"text","text":"A container view controller owns a menu view controller and a content view controller."}],"type":"topic","navigatorTitle":[{"text":"SideMenuController","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideMenuController"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","url":"\/documentation\/sidemenu\/sidemenucontroller"},"doc://com.kukushi.SideMenu/objc(cs)UIStoryboardSegue":{"type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/objc(cs)UIStoryboardSegue","title":"UIStoryboardSegue"},"doc://com.kukushi.SideMenu/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.kukushi.SideMenu/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.kukushi.SideMenu/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.kukushi.SideMenu/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/contentType-swift.property":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"current content type"}],"url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.property","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/contentType-swift.property","title":"contentType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SideMenu@objc(cs)SideMenuSegue","text":"SideMenuSegue"},{"text":".","kind":"text"},{"text":"ContentType","preciseIdentifier":"s:8SideMenu0aB5SegueC11ContentTypeO","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.kukushi.SideMenu/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/SH"},"doc://com.kukushi.SideMenu/documentation/SideMenu":{"role":"collection","url":"\/documentation\/sidemenu","kind":"symbol","title":"SideMenu","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu","abstract":[],"type":"topic"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue":{"abstract":[{"text":"Custom Segue that is required for ","type":"text"},{"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuController","type":"reference","isActive":true},{"type":"text","text":" to be used in Storyboard."}],"role":"symbol","identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SideMenuSegue","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sidemenu\/sidemenusegue","title":"SideMenuSegue","type":"topic","navigatorTitle":[{"text":"SideMenuSegue","kind":"identifier"}]},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/perform()":{"role":"symbol","type":"topic","abstract":[{"text":"Performing the segue, will change the corresponding view controller of side menu to ","type":"text"},{"type":"codeVoice","code":"destination"},{"text":" view controller.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This method is called when loading from storyboard."}],"url":"\/documentation\/sidemenu\/sidemenusegue\/perform()","navigatorTitle":[{"text":"perform","kind":"identifier"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/perform()","title":"perform()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"perform"},{"text":"()","kind":"text"}],"kind":"symbol"},"doc://com.kukushi.SideMenu/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.kukushi.SideMenu\/SQ","title":"Swift.Equatable"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/ContentType-swift.enum":{"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/ContentType-swift.enum","navigatorTitle":[{"kind":"identifier","text":"ContentType"}],"role":"symbol","title":"SideMenuSegue.ContentType","abstract":[{"type":"text","text":"The type of segue"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContentType"}],"type":"topic","url":"\/documentation\/sidemenu\/sidemenusegue\/contenttype-swift.enum","kind":"symbol"},"doc://com.kukushi.SideMenu/documentation/SideMenu/SideMenuSegue/initWithIdentifier:source:destination:":{"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/sidemenu\/sidemenusegue\/initwithidentifier:source:destination:","navigatorTitle":[{"kind":"identifier","text":"initWithIdentifier:source:destination:"}],"identifier":"doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/initWithIdentifier:source:destination:","title":"initWithIdentifier:source:destination:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithIdentifier:source:destination:"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SideMenuSegue","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SideMenuSegue"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SideMenuSegue"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/initWithIdentifier:source:destination:","doc:\/\/com.kukushi.SideMenu\/documentation\/SideMenu\/SideMenuSegue\/perform()"]}],"op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.kukushi.SideMenu\/objc(cs)UIStoryboardSegue"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SideMenuSegue"},{"text":" : ","kind":"text"},{"text":"UIStoryboardSegue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIStoryboardSegue"}],"languages":["occ"]}]}},{"value":"SideMenuController","op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/title"},{"value":[{"kind":"identifier","text":"SideMenuController"}],"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuController\/fragments"},{"value":"SideMenuSegue","op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/title"},{"value":[{"text":"SideMenuSegue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue~1perform()\/title","value":"perform","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.kukushi.SideMenu~1documentation~1SideMenu~1SideMenuSegue~1perform()\/fragments","value":[{"kind":"text","text":"- "},{"text":"perform","kind":"identifier"}]}]}]}